version: "3"

services:
  neo4j:
    image: neo4j:4.3.4
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=none

  app:
    build:
      context: .
    ports:
      - "4000:80"
